### ISSUE TITLE
Issue when the same line occurs odd times

### ISSUE THREAD

**Issue by caramdache** [breezy-team/patiencediff#42]
If the exact same line occurs `n`-times, where `n` is odd, won't that line end-up in `index` when it should not? 

https://github.com/breezy-team/patiencediff/blob/46788d7de9548b993127a25ca373c9d782104760/patiencediff/_patiencediff_py.py#L46-L50

**Comment by jelmer** [comment]
I'm not sure I understand the comment. Do you perhaps have an example input that fails?

**Comment by caramdache** [comment]
My understanding of the patience algorithm is that it will look for lines that appear once only in each file to create the skeleton diff document. Then it will work on the remaining sections.

So if a line appears more than once, it will not be accounted for in pass 1. However, the code above seems to be working differently: when a third identical line is found, it will set `index[line] = i`, instead of keeping `index[line] = None`.

But maybe my understanding of the patience algorithm is incorrect.

**Comment by jelmer** [comment]
I don't see why it would do that when the third identical line is found.

When a third identical line is found, "line" is still present in "index" so index[line] will be set to None (which it should already be).

Do you have a test case that reproduces this, or is this just based on reading the code?

**Comment by caramdache** [comment]
> When a third identical line is found, "line" is still present in "index"

No, because it has been set to `None` when the 2nd occurence was found.

**Comment by jelmer** [comment]
I'm not sure that I follow - assigning none to a dictionary key doesn't delete that key:

```python
>>> x = {}
>>> x["foo"] = None
>>> "foo" in x
True
>>>
```

**Comment by jelmer** [comment]
Closing this for now - feel free to reopen if you still believe there is a bug here. Ideally with an example to reproduce the bug.
